%% Part 0 - Generacio de Taula d'entrades
% Aquesta part es simplement de manipluacio de dades

% Accedim a les imatges
flatImgs = dir(fullfile('TRAIN', '**', '*.jpg'));
numImgs = length(flatImgs);
idx = randperm(numImgs); % Fem un shuffle per no tenir biaixos(vec - idx)
% Estructura de la Taula de Entrades
data = struct('img', {}, 'classname', {}, 'test', {});
counter = 1;

numTrain = floor(0.7 * numImgs);
for k = 1:numImgs
  filename = flatImgs(idx(k)).name;
  folderPath = flatImgs(idx(k)).folder; % Ruta completa de la carpeta
  [~, className, ~] = fileparts(folderPath); % Nom de la carpeta
  data(counter).img = fullfile('TRAIN', className, filename);  
  data(counter).classname = className;
  isTest = k > numTrain; % Llindar d'entrenament
  data(counter).test = isTest;
  counter = counter + 1;
end

T = struct2table(data); % Creem la taula
%disp(T(1:min(10, height(T)), :)); % El header de la taula
mapa_series = containers.Map( ...
   {'barrufets', 'Bob esponja', 'gat i gos', 'Gumball', ...
    'hora de aventuras', 'Oliver y Benji', 'padre de familia', ...
    'pokemon', 'southpark', 'Tom y Jerry'}, ...
   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
nom2num = zeros(height(T), 1); %Inicialitzem la nova columna
for i = 1:height(T)
   nom = char(T{i,2}); 
   nom2num(i) = mapa_series(nom); % Passem el map pels noms de T
end
T.codiSerie = nom2num;
save('taulaEntrades.mat', 'T');
%% Part 1 - Descriptor de les Sèries
T = load("./taulaEntrades.mat").T;

flatImgs = dir(fullfile('TRAIN', '**', '*.jpg'));
numImgs = length(flatImgs);

classNames = {'barrufets', 'Bob esponja', 'gat i gos', 'Gumball', ...
              'hora de aventuras', 'Oliver y Benji', 'padre de familia', ...
              'pokemon', 'southpark', 'Tom y Jerry'};
numClasses = length(classNames);

% COLOR
nbins = 8;
numColorFeatures = nbins^3;

X = zeros(numImgs, numColorFeatures);  % Cada fila histograma per img
Y = zeros(numImgs, 1);                 % Clases

for k = 1 : numImgs
    filename = flatImgs(k).name;
    folderPath = flatImgs(k).folder;          % Ruta completa de la carpeta
    [~, className, ~] = fileparts(folderPath); % Nom de la carpeta
    fullPath = fullfile(folderPath, filename);

    img = imread(fullPath);
    img = imresize(img, [128, 128]);

    % COLOR HISTOGRAM
    R = img(:,:,1);
    G = img(:,:,2);
    B = img(:,:,3);

    % Convertim els valors de la IMG a el bin corresponent
    R_bin = floor(double(R) / (256 / nbins));
    G_bin = floor(double(G) / (256 / nbins));
    B_bin = floor(double(B) / (256 / nbins));

    % Convertim els bins a un Pla conjunt amb el seu valor en 1D
    index = R_bin * nbins^2 + G_bin * nbins + B_bin + 1;

    hist_vector = histcounts(index(:), 1:(nbins^3 + 1)); % 512 bins

    % Normalitzar Histograma
    hist_vector = hist_vector / sum(hist_vector);

    classIdx = find(strcmp(classNames, className));

    X(k, :) = hist_vector;
    Y(k) = classIdx;
end

featureTable = array2table(X);
featureTable.Class = categorical(Y);

trainedModelSerieColor = trainClassifierSerieColor(featureTable);

% Funcio Exportada de Classification Learner - minimitzar-la
function [trainedClassifier, validationAccuracy] = trainClassifierSerieColor(trainingData)
% Auto-generated by MATLAB on 08-Jun-2025 18:34:05
inputTable = trainingData;
predictorNames = {'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40', 'X41', 'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50', 'X51', 'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X59', 'X60', 'X61', 'X62', 'X63', 'X64', 'X65', 'X66', 'X67', 'X68', 'X69', 'X70', 'X71', 'X72', 'X73', 'X74', 'X75', 'X76', 'X77', 'X78', 'X79', 'X80', 'X81', 'X82', 'X83', 'X84', 'X85', 'X86', 'X87', 'X88', 'X89', 'X90', 'X91', 'X92', 'X93', 'X94', 'X95', 'X96', 'X97', 'X98', 'X99', 'X100', 'X101', 'X102', 'X103', 'X104', 'X105', 'X106', 'X107', 'X108', 'X109', 'X110', 'X111', 'X112', 'X113', 'X114', 'X115', 'X116', 'X117', 'X118', 'X119', 'X120', 'X121', 'X122', 'X123', 'X124', 'X125', 'X126', 'X127', 'X128', 'X129', 'X130', 'X131', 'X132', 'X133', 'X134', 'X135', 'X136', 'X137', 'X138', 'X139', 'X140', 'X141', 'X142', 'X143', 'X144', 'X145', 'X146', 'X147', 'X148', 'X149', 'X150', 'X151', 'X152', 'X153', 'X154', 'X155', 'X156', 'X157', 'X158', 'X159', 'X160', 'X161', 'X162', 'X163', 'X164', 'X165', 'X166', 'X167', 'X168', 'X169', 'X170', 'X171', 'X172', 'X173', 'X174', 'X175', 'X176', 'X177', 'X178', 'X179', 'X180', 'X181', 'X182', 'X183', 'X184', 'X185', 'X186', 'X187', 'X188', 'X189', 'X190', 'X191', 'X192', 'X193', 'X194', 'X195', 'X196', 'X197', 'X198', 'X199', 'X200', 'X201', 'X202', 'X203', 'X204', 'X205', 'X206', 'X207', 'X208', 'X209', 'X210', 'X211', 'X212', 'X213', 'X214', 'X215', 'X216', 'X217', 'X218', 'X219', 'X220', 'X221', 'X222', 'X223', 'X224', 'X225', 'X226', 'X227', 'X228', 'X229', 'X230', 'X231', 'X232', 'X233', 'X234', 'X235', 'X236', 'X237', 'X238', 'X239', 'X240', 'X241', 'X242', 'X243', 'X244', 'X245', 'X246', 'X247', 'X248', 'X249', 'X250', 'X251', 'X252', 'X253', 'X254', 'X255', 'X256', 'X257', 'X258', 'X259', 'X260', 'X261', 'X262', 'X263', 'X264', 'X265', 'X266', 'X267', 'X268', 'X269', 'X270', 'X271', 'X272', 'X273', 'X274', 'X275', 'X276', 'X277', 'X278', 'X279', 'X280', 'X281', 'X282', 'X283', 'X284', 'X285', 'X286', 'X287', 'X288', 'X289', 'X290', 'X291', 'X292', 'X293', 'X294', 'X295', 'X296', 'X297', 'X298', 'X299', 'X300', 'X301', 'X302', 'X303', 'X304', 'X305', 'X306', 'X307', 'X308', 'X309', 'X310', 'X311', 'X312', 'X313', 'X314', 'X315', 'X316', 'X317', 'X318', 'X319', 'X320', 'X321', 'X322', 'X323', 'X324', 'X325', 'X326', 'X327', 'X328', 'X329', 'X330', 'X331', 'X332', 'X333', 'X334', 'X335', 'X336', 'X337', 'X338', 'X339', 'X340', 'X341', 'X342', 'X343', 'X344', 'X345', 'X346', 'X347', 'X348', 'X349', 'X350', 'X351', 'X352', 'X353', 'X354', 'X355', 'X356', 'X357', 'X358', 'X359', 'X360', 'X361', 'X362', 'X363', 'X364', 'X365', 'X366', 'X367', 'X368', 'X369', 'X370', 'X371', 'X372', 'X373', 'X374', 'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X381', 'X382', 'X383', 'X384', 'X385', 'X386', 'X387', 'X388', 'X389', 'X390', 'X391', 'X392', 'X393', 'X394', 'X395', 'X396', 'X397', 'X398', 'X399', 'X400', 'X401', 'X402', 'X403', 'X404', 'X405', 'X406', 'X407', 'X408', 'X409', 'X410', 'X411', 'X412', 'X413', 'X414', 'X415', 'X416', 'X417', 'X418', 'X419', 'X420', 'X421', 'X422', 'X423', 'X424', 'X425', 'X426', 'X427', 'X428', 'X429', 'X430', 'X431', 'X432', 'X433', 'X434', 'X435', 'X436', 'X437', 'X438', 'X439', 'X440', 'X441', 'X442', 'X443', 'X444', 'X445', 'X446', 'X447', 'X448', 'X449', 'X450', 'X451', 'X452', 'X453', 'X454', 'X455', 'X456', 'X457', 'X458', 'X459', 'X460', 'X461', 'X462', 'X463', 'X464', 'X465', 'X466', 'X467', 'X468', 'X469', 'X470', 'X471', 'X472', 'X473', 'X474', 'X475', 'X476', 'X477', 'X478', 'X479', 'X480', 'X481', 'X482', 'X483', 'X484', 'X485', 'X486', 'X487', 'X488', 'X489', 'X490', 'X491', 'X492', 'X493', 'X494', 'X495', 'X496', 'X497', 'X498', 'X499', 'X500', 'X501', 'X502', 'X503', 'X504', 'X505', 'X506', 'X507', 'X508', 'X509', 'X510', 'X511', 'X512'};
predictors = inputTable(:, predictorNames);
response = inputTable.Class;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'1'; '2'; '3'; '4'; '5'; '6'; '7'; '8'; '9'; '10'}, {'1' '2' '3' '4' '5' '6' '7' '8' '9' '10'});

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
subspaceDimension = max(1, min(256, width(predictors) - 1));
classificationEnsemble = fitcensemble(...
    predictors, ...
    response, ...
    'Method', 'Subspace', ...
    'NumLearningCycles', 30, ...
    'Learners', 'knn', ...
    'NPredToSample', subspaceDimension, ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
ensemblePredictFcn = @(x) predict(classificationEnsemble, x);
trainedClassifier.predictFcn = @(x) ensemblePredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40', 'X41', 'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50', 'X51', 'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X59', 'X60', 'X61', 'X62', 'X63', 'X64', 'X65', 'X66', 'X67', 'X68', 'X69', 'X70', 'X71', 'X72', 'X73', 'X74', 'X75', 'X76', 'X77', 'X78', 'X79', 'X80', 'X81', 'X82', 'X83', 'X84', 'X85', 'X86', 'X87', 'X88', 'X89', 'X90', 'X91', 'X92', 'X93', 'X94', 'X95', 'X96', 'X97', 'X98', 'X99', 'X100', 'X101', 'X102', 'X103', 'X104', 'X105', 'X106', 'X107', 'X108', 'X109', 'X110', 'X111', 'X112', 'X113', 'X114', 'X115', 'X116', 'X117', 'X118', 'X119', 'X120', 'X121', 'X122', 'X123', 'X124', 'X125', 'X126', 'X127', 'X128', 'X129', 'X130', 'X131', 'X132', 'X133', 'X134', 'X135', 'X136', 'X137', 'X138', 'X139', 'X140', 'X141', 'X142', 'X143', 'X144', 'X145', 'X146', 'X147', 'X148', 'X149', 'X150', 'X151', 'X152', 'X153', 'X154', 'X155', 'X156', 'X157', 'X158', 'X159', 'X160', 'X161', 'X162', 'X163', 'X164', 'X165', 'X166', 'X167', 'X168', 'X169', 'X170', 'X171', 'X172', 'X173', 'X174', 'X175', 'X176', 'X177', 'X178', 'X179', 'X180', 'X181', 'X182', 'X183', 'X184', 'X185', 'X186', 'X187', 'X188', 'X189', 'X190', 'X191', 'X192', 'X193', 'X194', 'X195', 'X196', 'X197', 'X198', 'X199', 'X200', 'X201', 'X202', 'X203', 'X204', 'X205', 'X206', 'X207', 'X208', 'X209', 'X210', 'X211', 'X212', 'X213', 'X214', 'X215', 'X216', 'X217', 'X218', 'X219', 'X220', 'X221', 'X222', 'X223', 'X224', 'X225', 'X226', 'X227', 'X228', 'X229', 'X230', 'X231', 'X232', 'X233', 'X234', 'X235', 'X236', 'X237', 'X238', 'X239', 'X240', 'X241', 'X242', 'X243', 'X244', 'X245', 'X246', 'X247', 'X248', 'X249', 'X250', 'X251', 'X252', 'X253', 'X254', 'X255', 'X256', 'X257', 'X258', 'X259', 'X260', 'X261', 'X262', 'X263', 'X264', 'X265', 'X266', 'X267', 'X268', 'X269', 'X270', 'X271', 'X272', 'X273', 'X274', 'X275', 'X276', 'X277', 'X278', 'X279', 'X280', 'X281', 'X282', 'X283', 'X284', 'X285', 'X286', 'X287', 'X288', 'X289', 'X290', 'X291', 'X292', 'X293', 'X294', 'X295', 'X296', 'X297', 'X298', 'X299', 'X300', 'X301', 'X302', 'X303', 'X304', 'X305', 'X306', 'X307', 'X308', 'X309', 'X310', 'X311', 'X312', 'X313', 'X314', 'X315', 'X316', 'X317', 'X318', 'X319', 'X320', 'X321', 'X322', 'X323', 'X324', 'X325', 'X326', 'X327', 'X328', 'X329', 'X330', 'X331', 'X332', 'X333', 'X334', 'X335', 'X336', 'X337', 'X338', 'X339', 'X340', 'X341', 'X342', 'X343', 'X344', 'X345', 'X346', 'X347', 'X348', 'X349', 'X350', 'X351', 'X352', 'X353', 'X354', 'X355', 'X356', 'X357', 'X358', 'X359', 'X360', 'X361', 'X362', 'X363', 'X364', 'X365', 'X366', 'X367', 'X368', 'X369', 'X370', 'X371', 'X372', 'X373', 'X374', 'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X381', 'X382', 'X383', 'X384', 'X385', 'X386', 'X387', 'X388', 'X389', 'X390', 'X391', 'X392', 'X393', 'X394', 'X395', 'X396', 'X397', 'X398', 'X399', 'X400', 'X401', 'X402', 'X403', 'X404', 'X405', 'X406', 'X407', 'X408', 'X409', 'X410', 'X411', 'X412', 'X413', 'X414', 'X415', 'X416', 'X417', 'X418', 'X419', 'X420', 'X421', 'X422', 'X423', 'X424', 'X425', 'X426', 'X427', 'X428', 'X429', 'X430', 'X431', 'X432', 'X433', 'X434', 'X435', 'X436', 'X437', 'X438', 'X439', 'X440', 'X441', 'X442', 'X443', 'X444', 'X445', 'X446', 'X447', 'X448', 'X449', 'X450', 'X451', 'X452', 'X453', 'X454', 'X455', 'X456', 'X457', 'X458', 'X459', 'X460', 'X461', 'X462', 'X463', 'X464', 'X465', 'X466', 'X467', 'X468', 'X469', 'X470', 'X471', 'X472', 'X473', 'X474', 'X475', 'X476', 'X477', 'X478', 'X479', 'X480', 'X481', 'X482', 'X483', 'X484', 'X485', 'X486', 'X487', 'X488', 'X489', 'X490', 'X491', 'X492', 'X493', 'X494', 'X495', 'X496', 'X497', 'X498', 'X499', 'X500', 'X501', 'X502', 'X503', 'X504', 'X505', 'X506', 'X507', 'X508', 'X509', 'X510', 'X511', 'X512'};
trainedClassifier.ClassificationEnsemble = classificationEnsemble;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2024b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplace ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40', 'X41', 'X42', 'X43', 'X44', 'X45', 'X46', 'X47', 'X48', 'X49', 'X50', 'X51', 'X52', 'X53', 'X54', 'X55', 'X56', 'X57', 'X58', 'X59', 'X60', 'X61', 'X62', 'X63', 'X64', 'X65', 'X66', 'X67', 'X68', 'X69', 'X70', 'X71', 'X72', 'X73', 'X74', 'X75', 'X76', 'X77', 'X78', 'X79', 'X80', 'X81', 'X82', 'X83', 'X84', 'X85', 'X86', 'X87', 'X88', 'X89', 'X90', 'X91', 'X92', 'X93', 'X94', 'X95', 'X96', 'X97', 'X98', 'X99', 'X100', 'X101', 'X102', 'X103', 'X104', 'X105', 'X106', 'X107', 'X108', 'X109', 'X110', 'X111', 'X112', 'X113', 'X114', 'X115', 'X116', 'X117', 'X118', 'X119', 'X120', 'X121', 'X122', 'X123', 'X124', 'X125', 'X126', 'X127', 'X128', 'X129', 'X130', 'X131', 'X132', 'X133', 'X134', 'X135', 'X136', 'X137', 'X138', 'X139', 'X140', 'X141', 'X142', 'X143', 'X144', 'X145', 'X146', 'X147', 'X148', 'X149', 'X150', 'X151', 'X152', 'X153', 'X154', 'X155', 'X156', 'X157', 'X158', 'X159', 'X160', 'X161', 'X162', 'X163', 'X164', 'X165', 'X166', 'X167', 'X168', 'X169', 'X170', 'X171', 'X172', 'X173', 'X174', 'X175', 'X176', 'X177', 'X178', 'X179', 'X180', 'X181', 'X182', 'X183', 'X184', 'X185', 'X186', 'X187', 'X188', 'X189', 'X190', 'X191', 'X192', 'X193', 'X194', 'X195', 'X196', 'X197', 'X198', 'X199', 'X200', 'X201', 'X202', 'X203', 'X204', 'X205', 'X206', 'X207', 'X208', 'X209', 'X210', 'X211', 'X212', 'X213', 'X214', 'X215', 'X216', 'X217', 'X218', 'X219', 'X220', 'X221', 'X222', 'X223', 'X224', 'X225', 'X226', 'X227', 'X228', 'X229', 'X230', 'X231', 'X232', 'X233', 'X234', 'X235', 'X236', 'X237', 'X238', 'X239', 'X240', 'X241', 'X242', 'X243', 'X244', 'X245', 'X246', 'X247', 'X248', 'X249', 'X250', 'X251', 'X252', 'X253', 'X254', 'X255', 'X256', 'X257', 'X258', 'X259', 'X260', 'X261', 'X262', 'X263', 'X264', 'X265', 'X266', 'X267', 'X268', 'X269', 'X270', 'X271', 'X272', 'X273', 'X274', 'X275', 'X276', 'X277', 'X278', 'X279', 'X280', 'X281', 'X282', 'X283', 'X284', 'X285', 'X286', 'X287', 'X288', 'X289', 'X290', 'X291', 'X292', 'X293', 'X294', 'X295', 'X296', 'X297', 'X298', 'X299', 'X300', 'X301', 'X302', 'X303', 'X304', 'X305', 'X306', 'X307', 'X308', 'X309', 'X310', 'X311', 'X312', 'X313', 'X314', 'X315', 'X316', 'X317', 'X318', 'X319', 'X320', 'X321', 'X322', 'X323', 'X324', 'X325', 'X326', 'X327', 'X328', 'X329', 'X330', 'X331', 'X332', 'X333', 'X334', 'X335', 'X336', 'X337', 'X338', 'X339', 'X340', 'X341', 'X342', 'X343', 'X344', 'X345', 'X346', 'X347', 'X348', 'X349', 'X350', 'X351', 'X352', 'X353', 'X354', 'X355', 'X356', 'X357', 'X358', 'X359', 'X360', 'X361', 'X362', 'X363', 'X364', 'X365', 'X366', 'X367', 'X368', 'X369', 'X370', 'X371', 'X372', 'X373', 'X374', 'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X381', 'X382', 'X383', 'X384', 'X385', 'X386', 'X387', 'X388', 'X389', 'X390', 'X391', 'X392', 'X393', 'X394', 'X395', 'X396', 'X397', 'X398', 'X399', 'X400', 'X401', 'X402', 'X403', 'X404', 'X405', 'X406', 'X407', 'X408', 'X409', 'X410', 'X411', 'X412', 'X413', 'X414', 'X415', 'X416', 'X417', 'X418', 'X419', 'X420', 'X421', 'X422', 'X423', 'X424', 'X425', 'X426', 'X427', 'X428', 'X429', 'X430', 'X431', 'X432', 'X433', 'X434', 'X435', 'X436', 'X437', 'X438', 'X439', 'X440', 'X441', 'X442', 'X443', 'X444', 'X445', 'X446', 'X447', 'X448', 'X449', 'X450', 'X451', 'X452', 'X453', 'X454', 'X455', 'X456', 'X457', 'X458', 'X459', 'X460', 'X461', 'X462', 'X463', 'X464', 'X465', 'X466', 'X467', 'X468', 'X469', 'X470', 'X471', 'X472', 'X473', 'X474', 'X475', 'X476', 'X477', 'X478', 'X479', 'X480', 'X481', 'X482', 'X483', 'X484', 'X485', 'X486', 'X487', 'X488', 'X489', 'X490', 'X491', 'X492', 'X493', 'X494', 'X495', 'X496', 'X497', 'X498', 'X499', 'X500', 'X501', 'X502', 'X503', 'X504', 'X505', 'X506', 'X507', 'X508', 'X509', 'X510', 'X511', 'X512'};
predictors = inputTable(:, predictorNames);
response = inputTable.Class;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'1'; '2'; '3'; '4'; '5'; '6'; '7'; '8'; '9'; '10'}, {'1' '2' '3' '4' '5' '6' '7' '8' '9' '10'});

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationEnsemble, 'KFold', 5);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');

end



%% Part 2 - Descriptor dels Personatges - Extracció keypoints i features
baseFolder = './personatgeEntenament';
personFolders = dir(baseFolder);
personFolders = personFolders([personFolders.isdir] & ~startsWith({personFolders.name}, '.'));

% Mapa de noms, hauria de funcionar amb tots, en el cas del meu cwd es
% ./personatgeEntrenament/bob i dins les jpg

personNames = {personFolders.name};
numClasses  = length(personNames);
nameToLabel = containers.Map(personNames, 1:numClasses);

% Nombre total d’imatges
totalImgs = 0;
for i = 1:numClasses
    imgs = dir(fullfile(baseFolder, personNames{i}, '**', '*.jpg'));
    totalImgs = totalImgs + numel(imgs);
end

% Paràmetres per als descriptors
numKeypoints = 10;
patchSize = 16;
nbins = 4; 

% Struct on es guardaran els punts
allPoints = struct();


for i = 1:numClasses
    personName = personNames{i};
    imgs = dir(fullfile(baseFolder, personName, '**', '*.jpg'));
    
    personatgePoints = struct();  % Estructura per personatge
    imgCounter = 1;

    for j = 1:numel(imgs)
        imgPath = fullfile(imgs(j).folder, imgs(j).name);
        img = imread(imgPath);

        % Seleccionar punts manualment
        points = getPoints(imgPath, numKeypoints);

        
        % Histograma local de cada patch
        localHists = zeros(numKeypoints, nbins^3);
        
        for k = 1:numKeypoints
            x = points(k,1);
            y = points(k,2);

            % Definim tamany patch sense sobresurtir la img
            x1 = max(round(x - patchSize/2), 1);
            y1 = max(round(y - patchSize/2), 1);
            x2 = min(x1 + patchSize - 1, size(img, 2));
            y2 = min(y1 + patchSize - 1, size(img, 1));

            patch = img(y1:y2, x1:x2, :);
            % Si el patch no arriba al tamany pot donar errors simplement 
            % fem resize(bilineal), el segur és que serà descartat
            patch = imresize(patch, [patchSize patchSize]);

            % Convertir a HSV
            hsvPatch = rgb2hsv(patch);
    
            H = hsvPatch(:,:,1);  % Hue en [0,1]
            S = hsvPatch(:,:,2);  % Saturació en [0,1]
            V = hsvPatch(:,:,3);  % Valor en [0,1]
    
            % Calcular bins
            H_bin = floor(H * nbins);
            S_bin = floor(S * nbins);
            V_bin = floor(V * nbins);
    
            % Si estem al limit despres, al passar a 1D, estarem fora de rang
            H_bin(H_bin == nbins) = nbins - 1;
            S_bin(S_bin == nbins) = nbins - 1;
            V_bin(V_bin == nbins) = nbins - 1;
    
            index = H_bin * nbins^2 + S_bin * nbins + V_bin + 1;
    
            % Com es una caracteristica local, ponderarem l'histograma
            % per no incloure info del fons
            sigma = patchSize / 4;
            weights = fspecial('gaussian', [patchSize patchSize], sigma);
    
            % accumarray: color pixel + pes --> sortida
            hist_vector = accumarray(index(:), weights(:), [nbins^3, 1])';
            hist_vector = hist_vector / sum(hist_vector); % Nromalitzar

            localHists(k, :) = hist_vector;
        end

        % Desar a l’estructura
        personatgePoints(imgCounter).label = nameToLabel(personName);
        personatgePoints(imgCounter).name = imgs(j).name;
        personatgePoints(imgCounter).path = imgPath;
        personatgePoints(imgCounter).points = points;
        personatgePoints(imgCounter).descriptors = localHists;

        imgCounter = imgCounter + 1;
    end

    save(['descriptors_' personName '.mat'], 'personatgePoints');
end

save('manualKeypoints_HSV.mat', 'allPoints');

% --- Funció auxiliar ---
function points = getPoints(imagePath, numPoints)
    img = imread(imagePath);
    imshow(img);
    title(sprintf('Selecciona %d keypoints', numPoints));
    [x, y] = ginput(numPoints);
    points = [x, y];
    hold on;
    plot(x, y, 'ro', 'MarkerSize', 10, 'LineWidth', 2);
    hold off;
end

%% Part 3 - Validació dels descriptors de personatges

% La esctructura amb informacio dels personatge és la següent:
% label         name        path        points      descriptors
% numClasse   Imatge<i>   ubicacio    Loc.Punts  FeatureVec de cada punt
%                                   (10 * [x,y])  (10 * (4*4*4 bins))


descriptorFiles = dir('descriptors_*.mat');
personDescriptors = struct();
for i = 1:length(descriptorFiles)
    f = descriptorFiles(i).name;
    personatge = erase(f, {'descriptors_', '.mat'}); % extreu nomes el nom
    load(f, 'personatgePoints'); %carrega la estructura mencionada a dalt
    personDescriptors.(personatge) = personatgePoints;
end

% Paràmetres
patchSize = 16;
nbins = 4;
distThreshold = 0.22;
minUniqueDbPoints = 4;

% Carpeta amb imatges de TEST, aquetses imatges es recorreran per saber a
% on pertanyen i si el personatge es undefined o no(nomes Bob).
% MODIFICAR LA LINEA SEGUENT PER PROVAR EL SCRIPT
imageFolder = fullfile('test/');

imageFiles = dir(fullfile(imageFolder, '**', '*.jpg'));  % inclou subcarpetes

serieToPersonatges = containers.Map(...
    {'barrufets', 'Bob esponja', 'gat i gos', 'Gumball', ...
     'hora de aventures', 'Oliver y Benji', 'padre de familia', ...
     'pokemon', 'southpark', 'Tom y Jerry'}, ...
    {{'undefined'}, {'bob'}, {'undefined'}, {'undefined'}, ...
     {'undefined'}, {'undefined'}, {'undefined'}, ...
     {'undefined'}, {'undefined'}, {'tom'}});

for imgIdx = 1:length(imageFiles)
    testImgPath = fullfile(imageFiles(imgIdx).folder, imageFiles(imgIdx).name);
    testImg = imread(testImgPath);
    

    % Extraccio de caracteristiques -------------------------------------
    
    predictedSerie = predictSerieFromImage(testImg, trainedModelSerieColor);
    
    personatgesPossibles = serieToPersonatges(predictedSerie);
    
    % Detectar punts Harris 
    gray = rgb2gray(testImg);
    vertexs = detectHarrisFeatures(gray); 
    testPoints = vertexs.Location; % [x,y] dels KP, usat posteriorment
    numTestPoints = size(testPoints, 1);

    % Extreure descriptors HSV per a tots els punts 
    testDescriptors = zeros(numTestPoints, nbins^3);

    for k = 1:numTestPoints
        % Mateix codi que l'entrenament --------------------
        x = testPoints(k,1);
        y = testPoints(k,2);
        
        x1 = max(round(x - patchSize/2), 1);
        y1 = max(round(y - patchSize/2), 1);
        x2 = min(x1 + patchSize - 1, size(testImg, 2));
        y2 = min(y1 + patchSize - 1, size(testImg, 1));
        patch = testImg(y1:y2, x1:x2, :);
        patch = imresize(patch, [patchSize patchSize]);

        hsvPatch = rgb2hsv(patch);
        H = hsvPatch(:,:,1); S = hsvPatch(:,:,2); V = hsvPatch(:,:,3);  

        H_bin = floor(H * nbins); S_bin = floor(S * nbins); V_bin = floor(V * nbins);
        H_bin(H_bin == nbins) = nbins - 1; S_bin(S_bin == nbins) = nbins - 1;
        V_bin(V_bin == nbins) = nbins - 1;

        index = H_bin * nbins^2 + S_bin * nbins + V_bin + 1;
        sigma = patchSize / 4;
        weights = fspecial('gaussian', [patchSize patchSize], sigma);
        hist_vector = accumarray(index(:), weights(:), [nbins^3, 1])';
        hist_vector = hist_vector / sum(hist_vector); % Nromalitzar
        
        % Fi Mateix codi que l'entrenament --------------------
        testDescriptors(k, :) = hist_vector;
    end

    % Matching -------------------------------------------
    personNames = fieldnames(personDescriptors);
    numPersons = length(personNames);
    matchCounts = zeros(numPersons, 1);
    numUniqueMatches=0;
    matchedTestPointsIdx = [];
    
    for p = 1:numPersons
        personatge = personNames{p};
        trainData = personDescriptors.(personatge);
        bestMatches = [];
        % Per tota imatge d'entrenament
        for i = 1:length(trainData)
    
            % Descripotrs dels punts clau
            trainDescriptors = trainData(i).descriptors;
    
            % Distancia euclidea entre els punts de la imatge de test
            % i la de entrenament
            D = pdist2(testDescriptors, trainDescriptors);
            
            % pdist(nTestPointsx64, 10x64) retorna matriu
            % D(m,n) == distancia euclidea entre  
            % punt m de test i punt n de entrenament 
    
            for m = 1:size(D,1)
                % Per tot punt M, busquem la distancia minima als keypoints
                % de la imatge de test
                [minDist, idx] = min(D(m,:));
        
                % Guardem la info del millor match possible per poder 
                % fer un filtratge
                bestMatches = [bestMatches; struct( ...
                    'testIdx', m, ...
                    'dbImgIdx', i, ...
                    'trainPointIdx', idx, ...
                    'distance', minDist)];
            end
        end
        % Filtratge per distància
        filteredMatches = bestMatches([bestMatches.distance] < distThreshold);
        trainUniquePoints = unique([filteredMatches.trainPointIdx]);
        matchCounts(p) = length(trainUniquePoints);
    
        % Guardar KP de test si és el personatge de la predicció
        if strcmp(personatge, personatgesPossibles)
            matchedTestPointsIdx = unique([filteredMatches.testIdx]);
            numUniqueMatches=length(matchedTestPointsIdx);
        end
    end
    
    count = 0;
    % Visualitzacio -------------------------------------------
    imshow(testImg);
    hold on;
    

    % Dibuixar els keypoints de matches vàlids (només si hi ha)
    if ~isempty(matchedTestPointsIdx)
        plot(testPoints(matchedTestPointsIdx,1), testPoints(matchedTestPointsIdx,2), 'go', 'MarkerSize', 10, 'LineWidth', 2);
        
    end
    
    % Determinar personatge reconegut només si té prou matches i és bob o tom
    if (matchCounts(1) > minUniqueDbPoints) || (matchCounts(2) > minUniqueDbPoints)
        count = 3300;
        personatgeImg = personatgesPossibles{1};
    else 
        personatgeImg = 'undefined';
    end 
    

    fullTitle = sprintf('Serie: %s , Personatge:%s (bob: %d, tom: %d)', predictedSerie ,personatgeImg, matchCounts(1),matchCounts(2));
    hold off;
    title(fullTitle);
    waitforbuttonpress;
end

function predictedSerie = predictSerieFromImage(imgInput,trainedModelSerieColor)
    nbins = 8;

    % Leer o usar directamente la imagen si es un array
    if ischar(imgInput) || isstring(imgInput)
        img = imread(imgInput);
    else
        img = imgInput;
    end
    img = imresize(img, [128, 128]);

    % Calcular histograma RGB conjunto
    R = img(:,:,1);
    G = img(:,:,2);
    B = img(:,:,3);

    R_bin = floor(double(R) / (256 / nbins));
    G_bin = floor(double(G) / (256 / nbins));
    B_bin = floor(double(B) / (256 / nbins));

    index = R_bin * nbins^2 + G_bin * nbins + B_bin + 1;
    hist_vector = histcounts(index(:), 1:(nbins^3 + 1));
    hist_vector = hist_vector / sum(hist_vector);

    % Crear tabla con nombres de variables esperados por el modelo
    varNames = trainedModelSerieColor.RequiredVariables;
    X_test_table = array2table(hist_vector, 'VariableNames', varNames);

    % Predicción
    predictedLabel = trainedModelSerieColor.predictFcn(X_test_table);

    % Mapa de nombres de clases
    classNames = {'barrufets', 'Bob esponja', 'gat i gos', 'Gumball', ...
                  'hora de aventures', 'Oliver y Benji', 'padre de familia', ...
                  'pokemon', 'southpark', 'Tom y Jerry'};

    predictedIndex = double(predictedLabel);
    predictedSerie = classNames{predictedIndex};
end
